# Generated by Django 4.2.2 on 2023-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='default_images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'default_images',
            },
        ),
        migrations.CreateModel(
            name='user_upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='user_upload')),
            ],
            options={
                'db_table': 'user_upload',
            },
        ),
    ]
