# Generated by Django 4.2.2 on 2023-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='generated_memes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='memes')),
            ],
            options={
                'db_table': 'meme_generated',
            },
        ),
    ]
